(ns quickcheck.generators-test
  (:require [quickcheck.generators.auth :as auth]
            [quickcheck.generators.elite :as elite]
            [quickcheck.generators.email :as email]
            [quickcheck.generators.mac   :as mac]
            [clojure.test :refer :all]
            [clojure.test.check.clojure-test :refer (defspec)]
            [clojure.test.check.generators :as gen]
            [clojure.test.check.properties :as prop]))

(defspec dino-email-addresses
         (prop/for-all [e email/email]
                       (is (.contains e "@"))
                       (is (.contains e "aurus"))))

(defspec passwords
         (prop/for-all [pwd auth/dictionary-password]
                       (is (string? pwd))))

(defspec bearer-tokens
         (prop/for-all [token auth/bearer-token]
                       (is (string? token))
                       (is (= 32 (.length token)))))

; RAXXLA cannot be generated by the algorithm
; http://elite-dangerous.wikia.com/wiki/Raxxla
(defspec planets 1000
         (prop/for-all [planet elite/planet]
                       (is (string? planet))
                       (is (>= (.length planet) 2) planet)
                       (is (not= "RAXXLA" planet))))

(defspec mac-addresses
         (prop/for-all [mac mac/mac-address]
                       (is (string? mac))
                       (is (re-matches #"[a-f0-9]{2}(-[a-f0-9]{2}){5}" mac) mac)))
